In [1]:
# Ch 5 Matrix
import numpy as np

In [2]:
MatrixA = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
MatrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
MatrixB=np.array([[1,2],[3,4],[5,6],[7.8]])

In [5]:
MatrixB=np.array([[1,2],[3,4],[5,6],[7.8]])

In [6]:
MatrixC = np.ones([4,4], dtype=np.int32)

In [7]:
MatrixC

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [8]:
MatrixD = np.ones([4,4,4], dtype=np.bool)

In [9]:
MatrixD

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [10]:
MatrixE = np.mat([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
MatrixE

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
print(a*b)

[[ 1  4  9]
 [16 25 36]]


In [13]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(a.dot(b))

[[22 28 34]
 [49 64 79]]


In [14]:
changeIt = np.array([1,2,3,4,5,6,7,8])

print(changeIt)

print(changeIt.reshape(2,4))

print(changeIt.reshape(2,2,2))


[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
changeIt = np.array([[1,2,3,4],[5,6,7,8]])

print(np.transpose(changeIt))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [16]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
a = np.array([[1,2],[3,4]])
b = np.linalg.inv(a)

print(np.allclose(np.dot(a,b),np.identity(2)))


True


In [18]:
#Tensors
inputs = np.array([5,10,15])

In [19]:
weights = np.array([[.5,.2,-1],[.3,.4,.1],[-.2,.1,.3]])

In [20]:
result = np.dot(inputs,weights)
result

array([2.5, 6.5, 0.5])

In [21]:
def doAdd(a,b):
    return a+b
vectAdd = np.vectorize(doAdd)

print(vectAdd([1,2,3,4],[1,2,3,4]))

[2 4 6 8]


In [22]:
# Ch 6  Linear Regression
from sklearn.datasets import load_boston
from sklearn.preprocessing import scale
boston = load_boston()
X,y = scale(boston.data), boston.target

In [23]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [24]:
print('R2 %0.3f' % regression.score(X,y))

R2 0.741


In [25]:
print([a + ':' + str(round(b,1)) for a, b in zip(boston.feature_names,regression.coef_)])


['CRIM:-0.9', 'ZN:1.1', 'INDUS:0.1', 'CHAS:0.7', 'NOX:-2.1', 'RM:2.7', 'AGE:0.0', 'DIS:-3.1', 'RAD:2.7', 'TAX:-2.1', 'PTRATIO:-2.1', 'B:0.8', 'LSTAT:-3.7']


In [26]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
lbl = LabelEncoder()
enc = OneHotEncoder()
qualitative =['red','blue','green','red',
              'blue','green','red','blue']
labels = lbl.fit_transform(qualitative).reshape(8,1)
print(enc.fit_transform(labels).toarray())

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


/Users/apple/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [27]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

pf = PolynomialFeatures(degree=2)
poly_X = pf.fit_transform(X)
X_train, X_test, y_train, y_test =(train_test_split(poly_X, y, test_size = 0.33, random_state = 42))

from sklearn.linear_model import Ridge
reg_regression = Ridge(alpha=0.1, normalize=True)
reg_regression.fit(X_train, y_train)
print('R2: %0.3f' % r2_score(y_test, reg_regression.predict(X_test)))


R2: 0.820


In [28]:
import numpy as np

a = np.array([0,0,0,0,1,1,1,1])
b = np.array([1,2,3,4,5,6,7,8]).reshape(8,1)
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(b,a)
print(regression.predict(b)>0.5)

[False False False False  True  True  True  True]


In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

binary_y = np.array(y >= 40).astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, binary_y, test_size=0.33, random_state=5)
logistic = LogisticRegression()
logistic.fit(X_train, y_train)

from sklearn.metrics import accuracy_score
print('In-sample accuracy: %0.3f' % accuracy_score(y_train,logistic.predict(X_train)))
print('Out-sample accuracy:%0.3f' % accuracy_score(y_test, logistic.predict(X_test)))


In-sample accuracy: 0.973
Out-sample accuracy:0.958


/Users/apple/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [30]:
for var,coef in zip(boston.feature_names, logistic.coef_[0]):
    
        print('%7s: %7.3f' %(var,coef))

   CRIM:  -0.005
     ZN:   0.197
  INDUS:   0.580
   CHAS:  -0.023
    NOX:  -0.236
     RM:   1.426
    AGE:  -0.048
    DIS:  -0.365
    RAD:   0.645
    TAX:  -0.221
PTRATIO:  -0.554
      B:   0.049
  LSTAT:  -0.803


In [31]:
print('\nclasses:',logistic.classes_)
print('\nProbs:\n',logistic.predict_proba(X_test)[:3,:])
                                 


classes: [0 1]

Probs:
 [[0.39026273 0.60973727]
 [0.93857028 0.06142972]
 [0.98425591 0.01574409]]


In [32]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
check =[2**i for i in range(8)]
for i in range(2**7+1):
    X_train = np.column_stack((X_train, np.random.random(X_train.shape[0])))
    X_test = np.column_stack((X_test, np.random.random(X_test.shape[0])))
    regression.fit(X_train, y_train)
    if i in check:
        print('Random features: %i -> R2: %0.3f' %(i, r2_score(y_train, regression.predict(X_train))))
        

Random features: 1 -> R2: 0.740
Random features: 2 -> R2: 0.743
Random features: 4 -> R2: 0.744
Random features: 8 -> R2: 0.745
Random features: 16 -> R2: 0.749
Random features: 32 -> R2: 0.762
Random features: 64 -> R2: 0.790
Random features: 128 -> R2: 0.831


In [33]:
regression.fit(X_train, y_train)
print('R2 %0.3f'
    % r2_score(y_test,regression.predict(X_test)))

R2 0.529


In [34]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split

pf = PolynomialFeatures(degree=2)
poly_X = pf.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(poly_X, y, test_size=0.33, random_state=42)

from sklearn.linear_model import Ridge
reg_regression = Ridge(alpha=0.1, normalize=True)
reg_regression.fit(X_train, y_train)
print('R2:%0.3f' % r2_score(y_test, reg_regression.predict(X_test)))


R2:0.820
